Updated Stop auto-follow on scroll
glaslos/ochi pull request #21
Opened 2023-03-05 16:58 UTC by aditygrg2

Added support for stopping events when scrolled, and re-starting on clicking on an button. 

Issue : https://github.com/glaslos/ochi/issues/20

2023-03-06 06:32 UTC, aditygrg2 commented
Hello @glaslos, please check this PR, and let me know if I understood the requirement correctly

2023-03-06 08:16 UTC, glaslos requested changes

2023-03-06 08:16 UTC, glaslos commented on src/App.svelte
> +	$: eventStatus = showEvents;
Why are you using this proxy variable?

2023-03-06 08:16 UTC, glaslos commented on src/App.svelte
> +	$: if(eventStatus){
We don't want the event stream to stop, just auto follow be disabled for a period.

2023-03-07 04:46 UTC, aditygrg2 commented
Understood. I will update this PR accordingly

2023-03-07 07:47 UTC, aditygrg2 commented
Hi @glaslos,

I have tried these things while solving this problem -

1. I tried to control the scroll events through javascript, by analyzing that if the user is at the bottom (scrolled max), then I am updating the scroll values by maximum (scrollHeight - clientHeight), else the scroll value does not change and thus position remains intact. But this didn't work, as Svelte is updating changes but it is not considering and saving the scrolls, it is showing the element into view always.

2. In other frameworks like react, we can pass keys so that the re-rendering effect does not change or modify other properties of DOM, but I think in svelte passing keys is only limited to adding/removing elements and rendering them only from DOM and not modifying other properties

3. I tried modifying scroll-anchor property but still no success, as svelte was still scrolling as soon as the new event appears.

Can you please help me with any ideas or suggestions using which we can implement this?

2023-03-07 08:07 UTC, glaslos commented
@aditygrg2 I will give it a try after work. Sounds odd that this is a problem with Svelte 🤔

2023-03-11 20:45 UTC, glaslos commented
Have a look how it can be solve in #22

2023-03-11 20:50 UTC, aditygrg2 commented
Yes, got it, it was simple, I was going the tough way.

2023-03-11 20:50 UTC, closed without merging