Added config modal to support number of messages and dev/prod mode feature
glaslos/ochi pull request #29
Opened 2023-03-17 06:52 UTC by aditygrg2

Related to Issue #24 

PR #25

2023-03-17 06:53 UTC, aditygrg2 commented
@glaslos This PR is updated. Sorry for two closed PR's.

2023-03-17 08:46 UTC, glaslos commented
I'll have a look later. Be aware, that you can always fix issues in your PR via git, there should be no reasons for deleting a PR.

2023-03-18 11:06 UTC, glaslos requested changes

2023-03-18 11:06 UTC, glaslos commented on src/App.svelte
> +	} else{
Formatting

2023-03-18 11:06 UTC, glaslos commented on src/App.svelte
> +			conn = new WebSocket(`wss://${location.host}/subscribe`);
Here try to connect without SSL

2023-03-18 11:06 UTC, glaslos commented on src/App.svelte
> +	<backdrop id="backdrop" on:click={modalHandler} style="visibility: hidden;"></backdrop>
Why not use the Svelte modal? https://svelte.dev/examples/modal

2023-03-18 11:51 UTC, closed without merging